version: '3'

services:

  postgres:
    image: "postgres:alpine"
    container_name: drift-postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  mysql5:
    image: "mysql:5"
    container_name: drift-mysql5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
